# Plasmic workflow v4
name: Build and deploy Plasmic app

permissions:
  contents: write
  pages: write
  pull-requests: write

# on commit
on:
  push:
    branches:
      - main

jobs:
  job:
    name: Sync, build and deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checking out repository...
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - id: node
        name: Setting up node v18...
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - id: build
        name: Building...
        run: |
          yarn install
          yarn build
          ls -la