# Plasmic workflow v4
name: Build and deploy Plasmic app

permissions:
  contents: write
  pages: write
  pull-requests: write

on: [pull_request]

jobs:
  job:
    name: Build and deploy Plasmic App
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checking out repository...
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - id: node
        name: Setting up node v18...
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - id: build
        name: Building...
        run: |
            yarn install
            yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: |
            out