# Plasmic workflow v4
name: Build and deploy Plasmic app

permissions:
  contents: write
  pages: write
  pull-requests: write

on:
    workflow_run:
        workflows: ["Sync, build and deploy Plasmic app"]
        types:
        - completed

jobs:
  job:
    name: Build and deploy Plasmic App
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checking out repository...
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - id: node
        name: Setting up node v18...
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - id: build
        name: Building...
        run: |
            yarn install
            yarn build
      - id: deploy
        name: Deploying to S3...
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "out"
        